### PR TITLE
Build ETA and EMA on macOS

### PR DESCRIPTION
**Pull request by rdmitr**
It seems to be possible to build the ETA and EMA APIs on macOS with only a handful of minor tweaks which are not expected to affect the existing functionality.

Prior to running CMake, the following environment variables need to be set:

    export MACOSX_DEPLOYMENT_TARGET=10.14
    export OPENSSL_ROOT_DIR=/path/to/openssl1.0

Some of the applications and samples still fail to build. These must be disabled in CMake:

    cmake -DBUILD_ETA_EXAMPLES=Off -DBUILD_ETA_PERFTOOLS=Off -DBUILD_EMA_PERFTOOLS=Off -DCMAKE_BUILD_TYPE=Debug

### CODE REVIEW

**Comment by geoffmallard** [comment]
@rdmitr  Thank you for your contribution, our team is reviewing the Mac OS build support you have provided to incorporate it in a future release.

**Comment by vlevendel** [comment]
@rdmitr At this time, we have chosen not to support this OS.

**Comment by umernalla** [comment]
Hi @rdmitr - can you reach out to me please when you have a few minutes?
I am interested in getting some RT-DSK examples compiled and running on my Macbook - nothing official from the RT-SDK team - just for my convenience...
Thanks,
Umer Nalla

**Comment by rdmitr** [comment]
> Hi @rdmitr - can you reach out to me please when you have a few minutes? I am interested in getting some RT-DSK examples compiled and running on my Macbook - nothing official from the RT-SDK team - just for my convenience... Thanks, Umer Nalla

Hi Umer, not sure how to get in touch — please feel free to drop me a message at roman [at] dmitrienko [dot] com if I can be of any help

**Pull request closed without merging**
